### ISSUE TITLE
How to use it? guide me with. Thank you

### ISSUE THREAD

**Issue by Tomzen34** [huuhait/pubg-recoil#1]
How to use it? guide me with. Thank you

**Comment by huuhait** [comment]
Currently no guide 
I'll make this soon

**Comment by huuhait** [comment]
Checkout my first release exe easy to use
https://github.com/huuhait/pubg-recoil/releases/tag/v1.0.0
Remember install tesseract to make it work

Requirements:
- Resolution 2560x1440 only other will not work
- Tesseract

How to use:
- use `tab` open your inventory software will scan weapons and attachments (Automatic scan)
- use `1` or `2` to select weapon (Automatic select by scan weapon from first step)
- use `z` or `c` to shitdown or stand up (Automatic scan)
- use both `left click` and `right click` to fire and recoil make sure your bullets > 0
