### ISSUE TITLE
still can't run

### ISSUE THREAD

**Issue by hoangtung4398** [huuhait/pubg-recoil#3]
![image](https://github.com/huuhait/pubg-recoil/assets/127335579/e578339a-5e1a-4bb9-bb68-93d69489741b)
có thể hướng dẫn tôi chi tiết xíu dc ko

**Comment by 80381220** [comment]
Missing DLL

**Comment by huuhait** [comment]
you are missing dll
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z

try to download this
